name: portfolio
description: "Developer Haeheum's portfolio."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audioplayers: ^6.5.0
  flutter_shaders: ^0.1.3
  google_fonts: ^6.3.1
  http: ^1.5.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/sounds/bgm/
  shaders:
    - assets/shaders/water.frag
    - assets/shaders/glitch.frag
    - assets/shaders/pixelation.frag
    - assets/shaders/flashlight.frag
    - assets/shaders/ripple.frag
    - assets/shaders/smoke.frag
    - assets/shaders/magic.frag
    - assets/shaders/nightVision.frag
flutter_intl:
  enabled: true
