name: portfolio
description: "Developer Haeheum's portfolio."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audioplayers: ^6.0.0
  flutter_shaders: ^0.1.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: any
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/sounds/bgm/
  shaders:
    - assets/shaders/water.frag
flutter_intl:
  enabled: true
