name: portfolio
description: "Developer Haeheum's portfolio."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  google_fonts: ^6.2.1
  intl: any
  url_launcher: ^6.3.0
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/sounds/bgm/
flutter_intl:
  enabled: true
